<?php

namespace IbnZohr\ArchivesBundle\Repository;

/**
 * HospitalizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HospitalizationRepository extends \Doctrine\ORM\EntityRepository
{
}
