<?php

namespace IbnZohr\ArchivesBundle\Repository;

/**
 * OutgoingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutgoingRepository extends \Doctrine\ORM\EntityRepository
{
}
