<?php

namespace IbnZohr\ArchivesBundle\Repository;

/**
 * StoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoringRepository extends \Doctrine\ORM\EntityRepository
{
}
